### ISSUE TITLE
Left / Right arrow keys to fold

### ISSUE THREAD

**Issue by dufferzafar** [NikitaIvanovV/ictree#13]
Currently, up/down arrow keys can be used to traverse the tree, while enter folds / unfolds.

In other tree like controls (usually on GUIs), left / right arrow keys are used to unfold / fold an item

**Comment by NikitaIvanovV** [comment]
If what you're suggesting is more conventional, `ictree` should probably have those controls. However, right now left and arrow keys can be used if the text doesn't fit screen width (by pressing those keys you scroll horizontally).

**Comment by NikitaIvanovV** [comment]
Resolved in 67c72d4f7562ffed1f8a2227683f5f6ac74ffbe4

I forgot that one can also use `h` and `l` to scroll horizontally, so it's not a probem to use arrow keys for different action.

Thanks for the suggestion!

**Comment by dufferzafar** [comment]
Sorry, perhaps I should've clarified the behaviour more.

In tree views, say for eg in VS Code's left sidebar tree view & Qt GUI tree views, pressing `Left` on an item would:

- If it has children, and it is unfolded, then fold this item.
- If it has children, and it is folded, then go to it's parent.
- If it is a leaf (as in it doesn't have any children - so it can't be folded / unfolded) then go to it's parent.

Similarly, `Right` would unfold if an item if it is folded or just go to it's first child.

This allows us to quickly go up / down the tree.

**Comment by NikitaIvanovV** [comment]
Added proper behavior for Right arrow as well: 69e142ed32c414b17ce049b214b997afd8df302b
