### ISSUE TITLE
What would be cool....

### ISSUE THREAD

**Issue by xircon** [NikitaIvanovV/ictree#3]
* The ability to edit with the editor set in the environmental variable $EDITOR.
* View an image with the default image viewer (in my case imv)
You get the idea :smile:

**Comment by NikitaIvanovV** [comment]
Thanks for the suggestion! Frankly, I wouldn't like to turn `ictree` into another terminal file browser. However, I can see why one might need these features. What about a functionality to add custom keybindings that would invoke shell scripts? It would save me from adding every single file opener and at the same time give users an opportunity to extend the program however they want.

**Comment by NikitaIvanovV** [comment]
Resolved in bdb91a460b10d7fe62bea18960740db692a183d8: now you can define file openers in a config file. I've already wrote docs about it in the manpage.

**Comment by dufferzafar** [comment]
Yet another cool thing, since `ictree` can take a separator, we can use it with other tools as well:

https://github.com/orhun/systeroid: `systeroid -A | ictree -s . -f`
https://github.com/tomnomnom/gron:
`gron file.json | ictree -s . -f`

**Comment by NikitaIvanovV** [comment]
@dufferzafar Wow, I could not think of such a use case, thanks! Maybe it could be mentioned somewhere in the README?

**Comment by dufferzafar** [comment]
Yeah, most definitely, I'm pretty sure there would be other tools which could be used with ictree. Will let you know once I find them.
