### ISSUE TITLE
Consider porting this to FreeBSD, Windows, etc.

### ISSUE THREAD

**Issue by Tyler887** [NikitaIvanovV/ictree#9]
I feel this is only supported on GNU/Linux. There's already a `tree` command in every major OS and shell.
However, I would recommend that all software can be used on every OS. Consider making ports of ictree?

**Comment by NikitaIvanovV** [comment]
I cannot test it at the moment, but I think `ictree` should be able to get compiled on FreeBSD just fine. Regarding Windows, `ictree` is only useful in conjunction with other tools (like `locate` or `find`) and, as far as I know, there are no such tools on Windows.

**Comment by Tyler887** [comment]
> I cannot test it at the moment, but I think `ictree` should be able to get compiled on FreeBSD just fine. Regarding Windows, `ictree` is only useful in conjunction with other tools (like `locate` or `find`) and, as far as I know, there are no such tools on Windows.

If it works on FreeBSD, then will it work on similar systems (e.g. OpenBSD)?

**Comment by NikitaIvanovV** [comment]
I have no idea, I don't use those so I can't test them.

It would be awesome if someone running those system tested the program and told their experience here.

**Comment by Tyler887** [comment]
> I cannot test it at the moment, but I think `ictree` should be able to get compiled on FreeBSD just fine. Regarding Windows, `ictree` is only useful in conjunction with other tools (like `locate` or `find`) and, as far as I know, there are no such tools on Windows.

By the way, *Windows* has `where` instead of `find`. `find` on *Windows* actually searches in the file's text and is less used.
